[package]
name = "floating-cat"
version = "0.1.0"
edition = "2021"
authors = ["beetle"]
license = "MIT"
description = "allows f64s to be categorized"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
